import { User, Vault, Source, Annotation, AuditLog, VaultMember } from "@/types";

export const MOCK_USER: User = {
  id: "mock-user-001",
  name: "Seeri Ijj",
  username: "seeri_ijj",
  email: "seeri@gmail.com",
  avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj",
  isEmailVerified: true,
  loginProvider: "EMAIL",
  createdAt: "2025-01-15T10:00:00.000Z",
  updatedAt: "2026-06-05T08:00:00.000Z",
  plan: "FREE",
  aiUsage: {
    dailyUsed: 3,
    dailyLimit: 5,
    weeklyUsed: 9,
    weeklyLimit: 15,
  },
};

export const MOCK_MEMBERS: VaultMember[] = [
  {
    id: "mem-001",
    role: "OWNER",
    user: {
      id: "mock-user-001",
      name: "Seeri Ijj",
      email: "seeri@gmail.com",
      avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj",
    },
  },
  {
    id: "mem-002",
    role: "CONTRIBUTOR",
    user: {
      id: "mock-user-002",
      name: "Prof. Adrian Carter",
      email: "a.carter@researchlab.edu",
      avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Adrian",
    },
  },
  {
    id: "mem-003",
    role: "VIEWER",
    user: {
      id: "mock-user-003",
      name: "Elena Rostova",
      email: "e.rostova@uni.ac.uk",
      avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Elena",
    },
  },
];

export const MOCK_VAULTS: Vault[] = [
  {
    id: "vault-001",
    name: "AI & Neural Networks",
    description: "Deep-dive research vault for transformer architectures, attention mechanisms, and large-scale model training.",
    privacy: "PRIVATE",
    ownerId: "mock-user-001",
    myRole: "OWNER",
    createdAt: "2025-03-01T09:00:00.000Z",
    _count: { members: 3, files: 5, sources: 4 },
    owner: { name: "Seeri Ijj", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    members: MOCK_MEMBERS,
  },
  {
    id: "vault-002",
    name: "Quantum Computing Foundations",
    description: "Compilation of peer-reviewed papers on quantum entanglement, error correction, and qubit coherence timescales.",
    privacy: "PRIVATE",
    ownerId: "mock-user-001",
    myRole: "OWNER",
    createdAt: "2025-04-10T11:00:00.000Z",
    _count: { members: 1, files: 2, sources: 2 },
    owner: { name: "Seeri Ijj", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    members: [MOCK_MEMBERS[0]],
  },
  {
    id: "vault-003",
    name: "Genomics & Bioinformatics",
    description: "Collaborative vault for DNA sequencing analysis, CRISPR literature, and genome assembly pipelines.",
    privacy: "PUBLIC",
    ownerId: "mock-user-002",
    myRole: "CONTRIBUTOR",
    createdAt: "2025-05-22T14:00:00.000Z",
    _count: { members: 3, files: 7, sources: 3 },
    owner: { name: "Prof. Adrian Carter", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Adrian" },
    members: MOCK_MEMBERS,
  },
];

export const MOCK_SOURCES: Record<string, Source[]> = {
  "vault-001": [
    {
      id: "src-001",
      vaultId: "vault-001",
      title: "Attention Is All You Need",
      authors: ["Vaswani, A.", "Shazeer, N.", "Parmar, N.", "Uszkoreit, J."],
      publication: "NeurIPS 2017",
      year: 2017,
      externalUrl: null,
      sourceType: "PDF",
      fileId: "file-001",
      file: { fileName: "attention_is_all_you_need.pdf", fileUrl: "https://arxiv.org/pdf/1706.03762.pdf", fileSize: 3145728 },
      extractedText: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks. The Transformer architecture relies solely on attention mechanisms, dispensing with recurrence and convolutions entirely.",
      textExtractedAt: "2025-03-02T10:00:00.000Z",
      aiSummary: "This seminal paper introduces the Transformer architecture, which replaces recurrent and convolutional layers entirely with attention mechanisms. The key innovation is multi-head self-attention, which allows the model to attend to different positions from different representation subspaces simultaneously. The architecture achieves state-of-the-art results on machine translation tasks while being more parallelizable and requiring significantly less training time.",
      aiInsights: {
        researchProblem: "Existing sequence transduction models rely on recurrent or convolutional architectures which are inherently sequential and difficult to parallelize.",
        methodology: "Proposed the Transformer model using stacked self-attention and point-wise fully connected layers for both encoder and decoder.",
        keyFindings: [
          { finding: "Multi-head attention allows joint attention to information from different representation subspaces.", significance: "High" },
          { finding: "Positional encoding preserves sequence order information without recurrence.", significance: "High" },
          { finding: "Achieved 28.4 BLEU on WMT 2014 English-to-German, outperforming all existing models.", significance: "High" },
        ],
        contributions: ["Introduced the Transformer architecture", "Proposed multi-head attention mechanism", "Demonstrated SOTA performance on NLP benchmarks"],
        limitations: ["Quadratic complexity with sequence length limits scalability", "Requires large datasets to train effectively"],
        futureWork: ["Extending to images and audio modalities", "Reducing computational complexity for longer sequences"],
        datasets: ["WMT 2014 English-German", "WMT 2014 English-French"],
      },
      aiProcessedAt: "2025-03-02T10:30:00.000Z",
      chunksProcessed: true,
      createdAt: "2025-03-02T09:00:00.000Z",
      updatedAt: "2025-03-02T10:30:00.000Z",
    },
    {
      id: "src-002",
      vaultId: "vault-001",
      title: "BERT: Pre-training of Deep Bidirectional Transformers",
      authors: ["Devlin, J.", "Chang, M.", "Lee, K.", "Toutanova, K."],
      publication: "NAACL 2019",
      year: 2019,
      externalUrl: "https://arxiv.org/abs/1810.04805",
      sourceType: "WEB_ARTICLE",
      fileId: null,
      file: null,
      extractedText: "We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers.",
      textExtractedAt: "2025-03-05T11:00:00.000Z",
      aiSummary: "BERT introduces a deeply bidirectional pre-training approach using masked language modeling and next sentence prediction objectives. Fine-tuned BERT models obtain SOTA results on eleven NLP tasks.",
      aiInsights: null,
      aiProcessedAt: null,
      chunksProcessed: false,
      createdAt: "2025-03-05T09:00:00.000Z",
      updatedAt: "2025-03-05T11:00:00.000Z",
    },
    {
      id: "src-003",
      vaultId: "vault-001",
      title: "GPT-4 Technical Report",
      authors: ["OpenAI"],
      publication: "OpenAI Technical Report",
      year: 2023,
      externalUrl: "https://arxiv.org/abs/2303.08774",
      sourceType: "WEB_ARTICLE",
      fileId: null,
      file: null,
      extractedText: "GPT-4 is a large-scale, multimodal model which can accept image and text inputs and produce text outputs.",
      textExtractedAt: null,
      aiSummary: null,
      aiInsights: null,
      aiProcessedAt: null,
      chunksProcessed: false,
      createdAt: "2025-04-01T09:00:00.000Z",
      updatedAt: "2025-04-01T09:00:00.000Z",
    },
    {
      id: "src-004",
      vaultId: "vault-001",
      title: "Scaling Laws for Neural Language Models",
      authors: ["Kaplan, J.", "McCandlish, S.", "Henighan, T."],
      publication: "arXiv 2020",
      year: 2020,
      externalUrl: null,
      sourceType: "PDF",
      fileId: "file-004",
      file: { fileName: "scaling_laws_nlm.pdf", fileUrl: "https://arxiv.org/pdf/2001.08361.pdf", fileSize: 2097152 },
      extractedText: "We study empirical scaling laws for language model performance on the cross-entropy loss.",
      textExtractedAt: "2025-04-10T10:00:00.000Z",
      aiSummary: null,
      aiInsights: null,
      aiProcessedAt: null,
      chunksProcessed: true,
      createdAt: "2025-04-10T09:00:00.000Z",
      updatedAt: "2025-04-10T10:00:00.000Z",
    },
  ],
  "vault-002": [
    {
      id: "src-005",
      vaultId: "vault-002",
      title: "Quantum Supremacy Using a Programmable Superconducting Processor",
      authors: ["Arute, F.", "Arya, K.", "Babbush, R."],
      publication: "Nature 2019",
      year: 2019,
      externalUrl: null,
      sourceType: "PDF",
      fileId: "file-005",
      file: { fileName: "quantum_supremacy_google.pdf", fileUrl: "https://arxiv.org/pdf/1910.11333.pdf", fileSize: 4194304 },
      extractedText: "We report the use of a processor with programmable superconducting qubits to create quantum states on 53 qubits.",
      textExtractedAt: "2025-04-11T10:00:00.000Z",
      aiSummary: "Google AI demonstrates quantum supremacy with a 53-qubit processor completing a specific computation in 200 seconds that would take the world's fastest supercomputer 10,000 years.",
      aiInsights: null,
      aiProcessedAt: null,
      chunksProcessed: true,
      createdAt: "2025-04-11T09:00:00.000Z",
      updatedAt: "2025-04-11T10:00:00.000Z",
    },
    {
      id: "src-006",
      vaultId: "vault-002",
      title: "Quantum Error Correction: An Introductory Guide",
      authors: ["Devitt, S. J.", "Munro, W. J.", "Nemoto, K."],
      publication: "Contemporary Physics 2013",
      year: 2013,
      externalUrl: null,
      sourceType: "PDF",
      fileId: "file-006",
      file: { fileName: "qec_introductory_guide.pdf", fileUrl: "https://arxiv.org/pdf/0905.2794.pdf", fileSize: 1572864 },
      extractedText: "Quantum error correction is a fundamental concept in quantum information theory.",
      textExtractedAt: null,
      aiSummary: null,
      aiInsights: null,
      aiProcessedAt: null,
      chunksProcessed: false,
      createdAt: "2025-05-01T09:00:00.000Z",
      updatedAt: "2025-05-01T09:00:00.000Z",
    },
  ],
  "vault-003": [
    {
      id: "src-007",
      vaultId: "vault-003",
      title: "A Primer on CRISPR-Cas9 Gene Editing",
      authors: ["Doudna, J. A.", "Charpentier, E."],
      publication: "Science 2012",
      year: 2012,
      externalUrl: null,
      sourceType: "PDF",
      fileId: "file-007",
      file: { fileName: "crispr_primer_doudna.pdf", fileUrl: "https://arxiv.org/pdf/1911.03723.pdf", fileSize: 2621440 },
      extractedText: "CRISPR-Cas9 is a transformative genome editing technology derived from a bacterial immune system.",
      textExtractedAt: "2025-05-23T10:00:00.000Z",
      aiSummary: "This landmark paper describes the CRISPR-Cas9 mechanism — a RNA-guided endonuclease system that can be programmed to cut specific sequences in the genome. It revolutionized biotechnology by enabling precise, efficient, and low-cost genome editing across species.",
      aiInsights: null,
      aiProcessedAt: null,
      chunksProcessed: true,
      createdAt: "2025-05-23T09:00:00.000Z",
      updatedAt: "2025-05-23T10:00:00.000Z",
    },
  ],
};

export const MOCK_ANNOTATIONS: Record<string, Annotation[]> = {
  "src-001": [
    {
      id: "ann-001",
      sourceId: "src-001",
      vaultId: "vault-001",
      userId: "mock-user-001",
      contentMarkdown: "## Key Insight: Multi-Head Attention\n\nThe **multi-head attention** mechanism is the core innovation here. Rather than performing a single attention function, the model runs $h$ parallel attention heads:\n\n$$\\text{MultiHead}(Q, K, V) = \\text{Concat}(head_1, ..., head_h)W^O$$\n\nThis allows the model to jointly attend to information from **different representation subspaces** at different positions — something impossible with single-head attention.\n\n> Key implication: Each head can specialize in different syntactic or semantic relationships.",
      contentHtml: "<h2>Key Insight: Multi-Head Attention</h2>",
      pageReference: 4,
      sectionReference: "Section 3.2: Multi-Head Attention",
      version: 2,
      createdAt: "2025-03-10T14:00:00.000Z",
      updatedAt: "2025-03-15T09:00:00.000Z",
      author: {
        id: "mock-user-001",
        name: "Seeri Ijj",
        email: "seeri@gmail.com",
        avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj",
      },
    },
    {
      id: "ann-002",
      sourceId: "src-001",
      vaultId: "vault-001",
      userId: "mock-user-002",
      contentMarkdown: "## Positional Encoding Note\n\nThe positional encodings use **sine and cosine functions** of different frequencies:\n\n- $PE_{(pos, 2i)} = \\sin(pos / 10000^{2i/d_{model}})$\n- $PE_{(pos, 2i+1)} = \\cos(pos / 10000^{2i/d_{model}})$\n\nThis approach allows the model to generalize to sequence lengths **longer than those seen during training** — an important practical advantage over learned positional embeddings.\n\n> Critique: Fixed encodings may not optimally represent positional relationships for all tasks.",
      contentHtml: "<h2>Positional Encoding Note</h2>",
      pageReference: 6,
      sectionReference: "Section 3.5: Positional Encoding",
      version: 1,
      createdAt: "2025-03-12T16:00:00.000Z",
      updatedAt: "2025-03-12T16:00:00.000Z",
      author: {
        id: "mock-user-002",
        name: "Prof. Adrian Carter",
        email: "a.carter@researchlab.edu",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Adrian",
      },
    },
    {
      id: "ann-003",
      sourceId: "src-001",
      vaultId: "vault-001",
      userId: "mock-user-001",
      contentMarkdown: "## Scaled Dot-Product Attention — Why Scaling?\n\nThe paper scales the dot products by $\\frac{1}{\\sqrt{d_k}}$ before applying softmax. The rationale:\n\n- For **large values of $d_k$**, the dot products grow large in magnitude\n- This pushes the softmax into regions with **extremely small gradients**\n- The $\\sqrt{d_k}$ scaling keeps the variance of the dot products at 1\n\n> This is a subtle but critical implementation detail that stabilizes training significantly.",
      contentHtml: "<h2>Scaled Dot-Product Attention</h2>",
      pageReference: 4,
      sectionReference: "Section 3.2.1: Scaled Dot-Product Attention",
      version: 1,
      createdAt: "2025-03-14T11:00:00.000Z",
      updatedAt: "2025-03-14T11:00:00.000Z",
      author: {
        id: "mock-user-001",
        name: "Seeri Ijj",
        email: "seeri@gmail.com",
        avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj",
      },
    },
  ],
  "src-002": [
    {
      id: "ann-004",
      sourceId: "src-002",
      vaultId: "vault-001",
      userId: "mock-user-001",
      contentMarkdown: "## BERT Masked Language Modeling\n\nBERT's **Masked LM (MLM)** objective randomly masks 15% of input tokens and trains the model to predict them. This allows **bidirectional context** — unlike GPT's left-to-right approach.\n\nThe masking strategy:\n- 80% of the time: replace with `[MASK]`\n- 10% of the time: replace with random token  \n- 10% of the time: keep original token\n\n> This prevents the model from trivially learning to ignore `[MASK]` tokens at fine-tuning time.",
      contentHtml: "<h2>BERT Masked Language Modeling</h2>",
      pageReference: 3,
      sectionReference: "Section 3.1: Task #1: Masked LM",
      version: 1,
      createdAt: "2025-03-20T10:00:00.000Z",
      updatedAt: "2025-03-20T10:00:00.000Z",
      author: {
        id: "mock-user-001",
        name: "Seeri Ijj",
        email: "seeri@gmail.com",
        avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj",
      },
    },
  ],
  "src-005": [
    {
      id: "ann-005",
      sourceId: "src-005",
      vaultId: "vault-002",
      userId: "mock-user-001",
      contentMarkdown: "## Quantum Supremacy Definition\n\nThe paper defines quantum supremacy as the ability of a quantum processor to perform a **specific computational task** that would be practically impossible for any classical computer.\n\nThe task chosen: **Random Circuit Sampling** — generating samples from the output distribution of a random quantum circuit.\n\n> Important caveat: This does not mean quantum computers are universally faster. It demonstrates supremacy for *one specific task*.",
      contentHtml: "<h2>Quantum Supremacy Definition</h2>",
      pageReference: 2,
      sectionReference: "Introduction",
      version: 1,
      createdAt: "2025-04-15T10:00:00.000Z",
      updatedAt: "2025-04-15T10:00:00.000Z",
      author: {
        id: "mock-user-001",
        name: "Seeri Ijj",
        email: "seeri@gmail.com",
        avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj",
      },
    },
  ],
};

export const MOCK_AUDIT_LOGS: Record<string, AuditLog[]> = {
  "vault-001": [
    {
      id: "audit-001",
      vaultId: "vault-001",
      userId: "mock-user-001",
      action: "SOURCE_ADDED",
      entityType: "Source",
      entityId: "src-001",
      details: "Added source: Attention Is All You Need",
      createdAt: "2025-03-02T09:05:00.000Z",
      user: { id: "mock-user-001", name: "Seeri Ijj", email: "seeri@gmail.com", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    },
    {
      id: "audit-002",
      vaultId: "vault-001",
      userId: "mock-user-001",
      action: "ANNOTATION_ADDED",
      entityType: "Annotation",
      entityId: "ann-001",
      details: "Added annotation on: Attention Is All You Need (Page 4)",
      createdAt: "2025-03-10T14:05:00.000Z",
      user: { id: "mock-user-001", name: "Seeri Ijj", email: "seeri@gmail.com", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    },
    {
      id: "audit-003",
      vaultId: "vault-001",
      userId: "mock-user-002",
      action: "ANNOTATION_ADDED",
      entityType: "Annotation",
      entityId: "ann-002",
      details: "Added annotation on: Attention Is All You Need (Page 6)",
      createdAt: "2025-03-12T16:05:00.000Z",
      user: { id: "mock-user-002", name: "Prof. Adrian Carter", email: "a.carter@researchlab.edu", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Adrian" },
    },
    {
      id: "audit-004",
      vaultId: "vault-001",
      userId: "mock-user-001",
      action: "ANNOTATION_UPDATED",
      entityType: "Annotation",
      entityId: "ann-001",
      details: "Updated annotation: Key Insight: Multi-Head Attention (v2)",
      createdAt: "2025-03-15T09:05:00.000Z",
      user: { id: "mock-user-001", name: "Seeri Ijj", email: "seeri@gmail.com", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    },
    {
      id: "audit-005",
      vaultId: "vault-001",
      userId: "mock-user-001",
      action: "SOURCE_ADDED",
      entityType: "Source",
      entityId: "src-002",
      details: "Added source: BERT: Pre-training of Deep Bidirectional Transformers",
      createdAt: "2025-03-05T09:05:00.000Z",
      user: { id: "mock-user-001", name: "Seeri Ijj", email: "seeri@gmail.com", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    },
  ],
  "vault-002": [
    {
      id: "audit-006",
      vaultId: "vault-002",
      userId: "mock-user-001",
      action: "SOURCE_ADDED",
      entityType: "Source",
      entityId: "src-005",
      details: "Added source: Quantum Supremacy Using a Programmable Superconducting Processor",
      createdAt: "2025-04-11T09:05:00.000Z",
      user: { id: "mock-user-001", name: "Seeri Ijj", email: "seeri@gmail.com", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
    },
  ],
  "vault-003": [
    {
      id: "audit-007",
      vaultId: "vault-003",
      userId: "mock-user-002",
      action: "SOURCE_ADDED",
      entityType: "Source",
      entityId: "src-007",
      details: "Added source: A Primer on CRISPR-Cas9 Gene Editing",
      createdAt: "2025-05-23T09:05:00.000Z",
      user: { id: "mock-user-002", name: "Prof. Adrian Carter", email: "a.carter@researchlab.edu", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Adrian" },
    },
  ],
};

// Heatmap graph data for StatsTab (last 84 days)
export function generateMockHeatmapData() {
  const cells = [];
  const now = new Date();
  for (let i = 83; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    const count = Math.random() < 0.3 ? 0 : Math.floor(Math.random() * 8);
    cells.push({ date: d.toISOString().split("T")[0], count });
  }
  return cells;
}

export function generateMockUserStats(vaultId: string) {
  return [
    {
      user: { id: "mock-user-001", name: "Seeri Ijj", email: "seeri@gmail.com", avatar: "https://api.dicebear.com/7.x/pixel-art/svg?seed=SeerIjj" },
      totalCount: 14,
      actionCounts: { SOURCE_ADDED: 4, ANNOTATION_ADDED: 7, ANNOTATION_UPDATED: 3, FILE_UPLOADED: 2 },
    },
    {
      user: { id: "mock-user-002", name: "Prof. Adrian Carter", email: "a.carter@researchlab.edu", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Adrian" },
      totalCount: 8,
      actionCounts: { SOURCE_ADDED: 2, ANNOTATION_ADDED: 4, ANNOTATION_UPDATED: 2, FILE_UPLOADED: 1 },
    },
    {
      user: { id: "mock-user-003", name: "Elena Rostova", email: "e.rostova@uni.ac.uk", avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Elena" },
      totalCount: 3,
      actionCounts: { SOURCE_ADDED: 0, ANNOTATION_ADDED: 2, ANNOTATION_UPDATED: 1, FILE_UPLOADED: 0 },
    },
  ];
}
